#!/bin/sh

update-rc.d vtp-driver defaults
service vtp-driver restart

exit 0

#!/bin/sh
#
# postinstall script, created by checkinstall-1.6.2
#
depmod 4.15.0-29deepin-generic
#!/bin/sh
#
# postinstall script, created by checkinstall-1.6.2
#
depmod 4.15.0-29deepin-generic
