#!/bin/sh
module="virtual_touchpad"
device="virtual_touchpad"

# invoke rmmod with all arguments we got
/sbin/rmmod $module || exit 1

# Remove stale nodes

rm -f /dev/${device} /dev/${device}0

exit 0




